### ISSUE TITLE
[ENH] Modular Refactor

### ISSUE THREAD

**Issue by valkyrienyanko** [ibveecnk/iven.js#32]
The events and functions in your `index.js` file could be spread across multiple files.

E.g. `ready.js` and `message.js` could be in a Events folder.
E.g. Your FS file reader functions could be in a Loader.js module under Modules folder.

Let me know if you want this and I'll create a PR when I have time.

**Comment by ibveecnk** [comment]
If you would do that, I would really appreciate it

**Comment by valkyrienyanko** [comment]
I forgot to fork the repo and cloned it directly from your repo. I coded a lot and now git is saying refusing to merge unrelated histories. From my lack of experience with Git I'm going to halt my progress. If I would have forked your repo from the beginning, none of this hassle would have happened ,-, sorry.

I've uploaded what I've done to mega [here](https://mega.nz/file/fANDxaSa#b7ClOkkOektcPRybHHCj_xGj2tj6-rVHXwGmhT5BEjA).

Files I've modified are `index.js`, and everything under `Events` and `Modules` folders.

You can look at my [bot repo](https://github.com/valkyrienyanko/ValksBot) to get a general idea where I was going.

**Comment by ivbeck** [comment]
ok, thanks. I will take a look
